### PR TITLE
day04-bash & day05-bash

### PR DESCRIPTION
**Pull request by tholok97**
Day 4 in Bash.

Updated input and output with own data, as the output was missing. @Arxcis feel free to change this to your input/output pair for consistency.

Finally a task Bash handled well :yum:. Solve takes around a second.

Automatic test should run, but here is local output just in case:

```
tholok:~/code/forked$ npm run generate && npm run bash day04-respose-record/

> adventofcode2018@ generate /home/tholok/code/forked
> node generate.js

Generated day01-chronal-calibration/test.js
Generated day03-no-matter-how-you-slice-it/test.js
Generated day02-inventory-management-system/test.js
Generated day06-chronal-coordinates/test.js
Generated day04-respose-record/test.js
Generated day05-alchemical-reduction/test.js

> adventofcode2018@ bash /home/tholok/code/forked
> ava --verbose --match='*.bash' "day04-respose-record/"


  ✔ main.bash (112ms)

  1 test passed
```

## EDIT

See below for coments on day 5.

### CODE REVIEW

**Comment by tholok97** [comment]
I see you've used osx as the base for the Travis worker. I think that's why the Bash tests are failing here. Mac OSX is missing some `sed` featues I use: "https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed". It uses a very old version, so idk if we should change the Bash solutions to be portable to that old version, or if we should fix the worker and focus on the modern sed. :thinking:

**Comment by Arxcis** [comment]
I think i just have to install `gnu-sed` with brew
```
brew install gnu-sed --with-default-names
```
I will test if this solves the issue

**Comment by tholok97** [comment]
Okay everything back to normal. Local tests:

```
tholok:~/code/forked$ npm run generate && npm run bash day05-alchemical-reduction/

> adventofcode2018@ generate /home/tholok/code/forked
> node generate.js

Generated day02-inventory-management-system/test.js
Generated day01-chronal-calibration/test.js
Generated day03-no-matter-how-you-slice-it/test.js
Generated day04-respose-record/test.js
Generated day05-alchemical-reduction/test.js
Generated day06-chronal-coordinates/test.js

> adventofcode2018@ bash /home/tholok/code/forked
> ava --verbose --match='*.bash' "day05-alchemical-reduction/"


  ✔ main.bash (10.7s)

  1 test passed

tholok:~/code/forked$ npm run generate && npm run bash day04-respose-record/

> adventofcode2018@ generate /home/tholok/code/forked
> node generate.js

Generated day01-chronal-calibration/test.js
Generated day04-respose-record/test.js
Generated day03-no-matter-how-you-slice-it/test.js
Generated day02-inventory-management-system/test.js
Generated day05-alchemical-reduction/test.js
Generated day06-chronal-coordinates/test.js

> adventofcode2018@ bash /home/tholok/code/forked
> ava --verbose --match='*.bash' "day04-respose-record/"


  ✔ main.bash (105ms)

  1 test passed

tholok:~/code/forked$ git branch
  day06-bash
* master
```

**Comment by tholok97** [comment]
```
  /Users/travis/build/Arxcis/adventofcode2018/test-util.js:79
   78:         for (let i = 0; i < output.length; ++i) {     
   79:             t.is(output[i], expected[i], `Part${i+1}`)
   80:         }                                             
  Part1
  Difference:
  - '    9078'
  + '9078'
The command "node difftest.js" exited with 1.
```

There's spaces in the output from day5? :thinking: Runs fine locally:

```
tholok:~/code/forked$ npm run bash day05-alchemical-reduction/

> adventofcode2018@ bash /home/tholok/code/forked
> ava --verbose --match='*.bash' "day05-alchemical-reduction/"


  ✔ main.bash (12.7s)

  1 test passed
```

**Comment by tholok97** [comment]
I vote this PR isn't merged until the tests pass. :yum:  I can try and debug myself tomorrow.

No haste.

**Comment by tholok97** [comment]
Build passing :raised_hands: 

# The bug

The osx implementation of `wc` sometimes outputs leading spaces. I fixed it by removing leading spaces during `echo`. The code should now work fine for both Linux and osx :yum: 

Source: https://unix.stackexchange.com/questions/205906/extra-space-with-counted-line-number

**Comment by Arxcis** [comment]
Wow really interesting stuff you come over when trying to do tests across OS-es 👍  Good work!

**Pull request merged**
