### PR TITLE
Solves issue #27. Lowercased variables and fixed shellcheck warnings (Bash)

### PR DESCRIPTION
**Pull request by tholok97**
Solves issue #27.

Ouput from test and shellshock, since these aren't automatically run:

```
tholok:~/code/forked$ npm run bash

> adventofcode2018@ bash /home/tholok/code/forked
> ava --verbose --match='*.bash'


  ✖ No tests found in day04-respose-record/test.js
  ✖ No tests found in day05-alchemical-reduction/test.js
  ✔ day01-chronal-calibration › test › main.bash (10.6s)
  ✔ day02-inventory-management-system › test › main.bash (19.8s)
  ✔ day03-no-matter-how-you-slice-it › test › main.bash (3m 58.3s)

  3 tests passed

tholok:~/code/forked$ shellcheck day01-chronal-calibration/main.bash
tholok:~/code/forked$ shellcheck day02-inventory-management-system/main.bash
tholok:~/code/forked$ shellcheck day03-no-matter-how-you-slice-it/main.bash
```

# Notes about shellshock fixes

* Run with no options.
* Many "globbing" warnings. Reference: http://tldp.org/LDP/abs/html/globbingref.html. Fixed.
* Many `$ unnecessary inside $/${}` warnings. Fixed.

### CODE REVIEW

**Comment by tholok97** [comment]
Failed build output:

```
$ node difftest.js
git diff --name-only master
day01-chronal-calibration/main.bash
day02-inventory-management-system/main.bash
day03-no-matter-how-you-slice-it/main.bash
npm run bash day01-chronal-calibration/
npm run bash day02-inventory-management-system/
npm run bash day03-no-matter-how-you-slice-it/
> adventofcode2018@ bash /Users/travis/build/Arxcis/adventofcode2018
> ava --verbose --match='*.bash' "day01-chronal-calibration/"
  ✔ main.bash (19.9s)
  1 test passed
> adventofcode2018@ bash /Users/travis/build/Arxcis/adventofcode2018
> ava --verbose --match='*.bash' "day02-inventory-management-system/"
  ✔ main.bash (45.9s)
  1 test passed
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

The build fails after waiting 10 minutes. Day 3 takes around 4 minutes on my machine, as seen in the above comment. Day 1 and 2 is taking considerably longer on Travis than on my machine though, so maybe Travis is bad at Bash, and spens over 10 mins on day 3.

Either increase the max build time, or disable checks (again) for day3 bash? :yum:

**Comment by Arxcis** [comment]
Hey... You got to get yourself a better computer for bash programming :+1: Runs great on my 6-core intel i5
```
jonas in ~/git/github/arxcis/adventofcode2018 on 3632354
$ npm run bash

> adventofcode2018@ bash /home/jonas/git/github/arxcis/adventofcode2018
> ava --verbose --match='*.bash'


  ✖ No tests found in day05-alchemical-reduction/test.js
  ✖ No tests found in day04-respose-record/test.js
  ✔ day01-chronal-calibration › test › main.bash (4.7s)
  ✔ day02-inventory-management-system › test › main.bash (6.8s)
  ✔ day03-no-matter-how-you-slice-it › test › main.bash (49.7s)

  3 tests passed
```

Probably a good idea to blacklist individual files which has a known performance issue. At least until we get a special bash-optimized computer in the sky.  :P

**Comment by Arxcis** [comment]
> Could have a blacklist of what files not to automatically test?

I could also just merge even if Travis build fails, knowing that the reason not running fast enough.

Alternatively, ban languages which run to slow :+1:

**Comment by Arxcis** [comment]
> The build fails after waiting 10 minutes.

It's really wierd how slow `bash` is, considering `nodejs` runs the same task in 60 ms
```
$ time cat day03/input | node day03/main.js 
111630
724

real	0m0,068s
user	0m0,060s
sys	0m0,017s

$ time cat day01/input | bash day01/main.bash 
111630
724

real	0m50,523s
user	0m50,001s
sys	0m3,330s
```

**Comment by tholok97** [comment]
Guess it's just not built for Advent of Code :p (Won't stop me from trying)

**Comment by Arxcis** [comment]
> Guess it's just not built for Advent of Code :p (Won't stop me from trying)

I admire your persistence

**Pull request merged**
